package GUI;

import Entidad.Espacio;
import Entidad.Usuario;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class Frame_DetalleSolicitud extends javax.swing.JFrame {

    private int x,y;    
    private Frame_Main fraim;      
    public void Frame_DetallesSolicitud() {
        initComponents();
        this.setLocationRelativeTo(null);  
        habtext(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        paneldetallesInventario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextCorreoEncargado = new javax.swing.JTextField();
        jTextNombreEspacio2 = new javax.swing.JTextField();
        jTextCapacidad = new javax.swing.JTextField();
        jTextNombreEdificio = new javax.swing.JTextField();
        jTextNumeroSalon1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextNumeroEdificio3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextCorreoEncargado1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabelCargandoe = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCorreoEncargado2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextNombreEdificio1 = new javax.swing.JTextField();
        panelCerrar = new javax.swing.JPanel();
        jlClose1 = new javax.swing.JLabel();
        jlMinimize1 = new javax.swing.JLabel();
        LbUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(770, 617));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(640, 460));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneldetallesInventario.setBackground(new java.awt.Color(204, 204, 204));
        paneldetallesInventario.setMaximumSize(new java.awt.Dimension(640, 430));
        paneldetallesInventario.setMinimumSize(new java.awt.Dimension(640, 430));
        paneldetallesInventario.setPreferredSize(new java.awt.Dimension(640, 430));
        paneldetallesInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hora de inicio:");
        paneldetallesInventario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Observaciones:");
        paneldetallesInventario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de inicio:");
        paneldetallesInventario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Repetición:");
        paneldetallesInventario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nombre Edificio:");
        paneldetallesInventario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 110, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Salón:");
        paneldetallesInventario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Información del evento:");
        paneldetallesInventario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jTextCorreoEncargado.setEnabled(false);
        paneldetallesInventario.add(jTextCorreoEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 150, 30));

        jTextNombreEspacio2.setEnabled(false);
        paneldetallesInventario.add(jTextNombreEspacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, 30));

        jTextCapacidad.setEnabled(false);
        paneldetallesInventario.add(jTextCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 210, 80));

        jTextNombreEdificio.setEnabled(false);
        jTextNombreEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreEdificioActionPerformed(evt);
            }
        });
        paneldetallesInventario.add(jTextNombreEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 150, 30));

        jTextNumeroSalon1.setEnabled(false);
        paneldetallesInventario.add(jTextNumeroSalon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 70, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Dias:");
        paneldetallesInventario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 40, 20));

        jTextNumeroEdificio3.setEnabled(false);
        jTextNumeroEdificio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroEdificio3ActionPerformed(evt);
            }
        });
        paneldetallesInventario.add(jTextNumeroEdificio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 150, 30));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField2.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextField2.setEnabled(false);
        jTextField2.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        jTextField2.setSelectionColor(new java.awt.Color(204, 204, 204));
        paneldetallesInventario.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 150, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Motivo:");
        paneldetallesInventario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jTextCorreoEncargado1.setEnabled(false);
        paneldetallesInventario.add(jTextCorreoEncargado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 150, 30));

        jTextField3.setDisabledTextColor(new java.awt.Color(69, 73, 74));
        jTextField3.setEnabled(false);
        paneldetallesInventario.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, 30));
        paneldetallesInventario.add(jLabelCargandoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 100, 20));

        jTextField4.setDisabledTextColor(new java.awt.Color(69, 73, 74));
        jTextField4.setEnabled(false);
        paneldetallesInventario.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 150, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Fecha termina:");
        paneldetallesInventario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Hora final:");
        paneldetallesInventario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, 20));

        jTextCorreoEncargado2.setEnabled(false);
        paneldetallesInventario.add(jTextCorreoEncargado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 150, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Nombre del espacio:");
        paneldetallesInventario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, 20));

        jTextNombreEdificio1.setEnabled(false);
        jTextNombreEdificio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreEdificio1ActionPerformed(evt);
            }
        });
        paneldetallesInventario.add(jTextNombreEdificio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 150, 30));

        getContentPane().add(paneldetallesInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 430));

        panelCerrar.setBackground(new java.awt.Color(153, 153, 153));
        panelCerrar.setForeground(new java.awt.Color(102, 255, 255));
        panelCerrar.setMaximumSize(new java.awt.Dimension(50, 30));
        panelCerrar.setMinimumSize(new java.awt.Dimension(50, 30));
        panelCerrar.setPreferredSize(new java.awt.Dimension(500, 30));
        panelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/incorrecto.png"))); // NOI18N
        jlClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlClose1MouseClicked(evt);
            }
        });
        panelCerrar.add(jlClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 20, -1));

        jlMinimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/linea.png"))); // NOI18N
        jlMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimize1MouseClicked(evt);
            }
        });
        panelCerrar.add(jlMinimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 20, -1));

        LbUsuario.setBackground(new java.awt.Color(0, 51, 204));
        LbUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo u_preview_rev_1_opt.png"))); // NOI18N
        LbUsuario.setText("Horarios de salas TIC's y Laboratorios");
        panelCerrar.add(LbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 240, 20));

        getContentPane().add(panelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
     private void habilitarControles(JTextField text, boolean b) {
          if (b) {
              
                  text.setDisabledTextColor(new Color(0, 0, 0));
                  text.setBackground(new Color(255, 255, 255));
                  text.setEnabled(b);
            } else {
                  text.setDisabledTextColor(new Color(60, 63, 65));
                  text.setBackground(new Color(240, 240, 240));
                  text.setEnabled(b);
           }
              
        }
     
     private void habtext(boolean b){      
         habilitarControles(jTextNombreEspacio2,b);
         habilitarControles(jTextCorreoEncargado,b);
         habilitarControles(jTextCorreoEncargado1,b);
         habilitarControles(jTextCapacidad,b);
         habilitarControles(jTextNumeroSalon1,b);
         habilitarControles(jTextNumeroEdificio3,b);
         habilitarControles(jTextNombreEdificio,b);                        
         
     }
    public void llenarFrame(Usuario u, Espacio esp, Frame_Main frame) throws SQLException{
        
        this.fraim = frame;
        jTextCorreoEncargado.setText(esp.getNombre_tipoespacio());
        if(esp.getNombre_espacio().equals(null)){
             jTextNombreEspacio2.setText(" ");
        }else{
             jTextNombreEspacio2.setText(esp.getNombre_espacio());
        }
        jTextField2.setText(String.valueOf(esp.getId_espacio()));
        jTextField3.setText(esp.getNombre_tipoespacio());
        jTextCorreoEncargado.setText(esp.getCorreo_encargado());
        jTextCorreoEncargado1.setText(esp.getNombre_encargado());        
        jTextNumeroSalon1.setText(esp.getNum_Espacio());
        jTextNombreEdificio.setText(esp.getNombre_edificio());
        jTextNumeroEdificio3.setText(String.valueOf(esp.getNum_edificio()));     
        jTextCapacidad.setText(String.valueOf(esp.getCapacidad()));  
    }
    
      
    
    private void jlClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClose1MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el esta ventana?","Exit",dialog);        
        if(result == 0){
            this.fraim.setEnabled(true);            
            this.dispose();            
        }
      
    }//GEN-LAST:event_jlClose1MouseClicked

    private void jlMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimize1MouseClicked
        this.setState(Frame_Login.ICONIFIED);
    }//GEN-LAST:event_jlMinimize1MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         this.setLocation(this.getLocation().x + evt.getX()-x,this.getLocation().y+evt.getY()-y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x= evt.getX();   
        y= evt.getY(); 
    }//GEN-LAST:event_formMousePressed

    private void jTextNombreEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreEdificioActionPerformed
       
    }//GEN-LAST:event_jTextNombreEdificioActionPerformed

    private void jTextNumeroEdificio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroEdificio3ActionPerformed
   
    }//GEN-LAST:event_jTextNumeroEdificio3ActionPerformed

    private void jTextNombreEdificio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreEdificio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreEdificio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_DetallesEspacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_DetallesEspacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_DetallesEspacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_DetallesEspacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_DetallesEspacio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbUsuario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCargandoe;
    private javax.swing.JTextField jTextCapacidad;
    private javax.swing.JTextField jTextCorreoEncargado;
    private javax.swing.JTextField jTextCorreoEncargado1;
    private javax.swing.JTextField jTextCorreoEncargado2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextNombreEdificio;
    private javax.swing.JTextField jTextNombreEdificio1;
    private javax.swing.JTextField jTextNombreEspacio2;
    private javax.swing.JTextField jTextNumeroEdificio3;
    private javax.swing.JTextField jTextNumeroSalon1;
    private javax.swing.JLabel jlClose1;
    private javax.swing.JLabel jlMinimize1;
    private javax.swing.JPanel panelCerrar;
    private javax.swing.JPanel paneldetallesInventario;
    // End of variables declaration//GEN-END:variables
}
