/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Asus
 */

public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro
     */
    
    
    public Registro() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearUser = new javax.swing.JLabel();
        usuario_r = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        conf_contraseña = new javax.swing.JTextField();
        usuario_institucional_r = new javax.swing.JLabel();
        contraseña_r = new javax.swing.JLabel();
        conf_contraseña_r = new javax.swing.JLabel();
        dominioUn = new javax.swing.JLabel();
        si = new javax.swing.JCheckBox();
        codico_coordinador = new javax.swing.JTextField();
        no = new javax.swing.JCheckBox();
        coordinador = new javax.swing.JLabel();
        registrarse = new javax.swing.JButton();
        atras_r = new javax.swing.JButton();

        crearUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        crearUser.setText("Crear usuario");

        usuario_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_rActionPerformed(evt);
            }
        });

        usuario_institucional_r.setLabelFor(usuario_r);
        usuario_institucional_r.setText("Usuario institucional");

        contraseña_r.setLabelFor(contraseña);
        contraseña_r.setText("Contraseña");

        conf_contraseña_r.setLabelFor(conf_contraseña);
        conf_contraseña_r.setText("Confirmar contraseña");

        dominioUn.setText("@unal.edu.co");

        si.setText("Si");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });

        no.setText("No");

        coordinador.setText("¿Es usted cooordinador de espacio?");

        registrarse.setText("Registrarse");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        atras_r.setText("Atras");
        atras_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras_rActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(usuario_institucional_r)
                                    .addComponent(contraseña_r)
                                    .addComponent(conf_contraseña_r)
                                    .addComponent(coordinador))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(conf_contraseña)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(usuario_r, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dominioUn))
                                    .addComponent(contraseña)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(si)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(no)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codico_coordinador, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(crearUser)
                                .addGap(71, 71, 71))))
                    .addComponent(atras_r)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(registrarse)))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(crearUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario_institucional_r)
                    .addComponent(dominioUn))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contraseña_r))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conf_contraseña_r))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si)
                    .addComponent(no)
                    .addComponent(codico_coordinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordinador))
                .addGap(49, 49, 49)
                .addComponent(registrarse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(atras_r)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarseActionPerformed

    private void atras_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras_rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atras_rActionPerformed

    private void usuario_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_rActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras_r;
    private javax.swing.JTextField codico_coordinador;
    private javax.swing.JTextField conf_contraseña;
    private javax.swing.JLabel conf_contraseña_r;
    private javax.swing.JTextField contraseña;
    private javax.swing.JLabel contraseña_r;
    private javax.swing.JLabel coordinador;
    private javax.swing.JLabel crearUser;
    private javax.swing.JLabel dominioUn;
    private javax.swing.JCheckBox no;
    private javax.swing.JButton registrarse;
    private javax.swing.JCheckBox si;
    private javax.swing.JLabel usuario_institucional_r;
    private javax.swing.JTextField usuario_r;
    // End of variables declaration//GEN-END:variables
}
